language: java
jdk:
  - openjdk8
servies:
  - docker
script:
  - ./gradlew build
  - env
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin;
    docker image build -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest .;
    docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest;
    fi