language: java
jdk:
  - openjdk8
servies:
  - docker
script:
  - env
  - if [ "$TRAVIS_BRANCH" = "javidy_5" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME -password-stdin;
    fi
