version: '2.1'
services:
    tasker-backend:
        image: jasb1025/tasker-backend:0.0.1
        container_name: tasker-backend
        ports:
            - "8080:8080"
    postgres:
        image: postgres:10.13
        environment:
            - POSTGRES_USER=tasker
            - POSTGRES_PASSWORD=tasker
            - POSTGRES_DB=taskerdb
        ports:
            - "5555:5432"

