version: '2.1'
services:
    tasker-backend:
        image: tasker-backend:latest
        container_name: tasker-backend
        #volumes:
        #    - ./build/libs:/home/app
        ports:
            - "8080:8080"
