version: '3.8'
services:
    tasker-backend:
        image: jasb1025/tasker-backend:latest
        container_name: tasker-backend
        ports:
            - "8080:8080"
        depends_on:
            - "postgres"
    postgres:
        image: postgres:10.13
        environment:
            - POSTGRES_USER=tasker
            - POSTGRES_PASSWORD=tasker
            - POSTGRES_DB=taskerdb
        ports:
            - "5555:5432"

